### PR TITLE
Fix datefield month january

### LINKED ISSUE #515: Date of birth is not properly displayed on hard refresh
The split date input (day/month/year) chokes om something - when entering 1/1/1980, submitting the step and then navigating back to step (potentially also hard refreshing it) seems to clear the month field, while the date entered *is* valid.

Potentially this has something to do with Javascript's bizarre month-0 indexing/numbering?

### PR DESCRIPTION
**Pull request by sergei-maertens**
Closes #515

### CODE REVIEW

File: src/components/forms/DateField/utils.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ export const getDateLocaleMeta = locale => {
 };
 
 export const convertMonth = (month, toAdd) => {
-  if (!month) return '';
+  if (month === '' || month == null) return '';
   const monthNumber = parseInt(month);
   return String(monthNumber + toAdd);
```
Comment (CharString) [inline src/components/forms/DateField/utils.js:52]:
```suggestion
  const monthNumber = parseInt(month);
  return isNaN(monthNumber)?'':String(monthNumber + toAdd);
```

This catches `undefined` and whatever JS idiosyncrasies  I haven't thought of.
Is it okay for this to go out of bounds to 13? :thinking: 12?

**Review by CharString — CHANGES_REQUESTED** [review]

File: src/components/forms/DateField/utils.js (hunk 1 above)
Comment (sergei-maertens) [reply src/components/forms/DateField/utils.js:52]: Undefined is already caught with the non-strict equal null. This is ugly but idiomatic javascript.

13 and the likes should be covered later when a date instance is constructed and checked against isNaN

**Review by CharString — APPROVED** [review]
